# Generated by Django 4.2.5 on 2023-09-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nguoidung',
            fields=[
                ('tendangnhap', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TENDANGNHAP', max_length=20, primary_key=True, serialize=False)),
                ('matkhau', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MATKHAU', max_length=20)),
                ('khoa', models.BooleanField(db_column='KHOA')),
                ('ho', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='HO', max_length=50)),
                ('ten', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TEN', max_length=20)),
                ('gioitinh', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='GIOITINH', max_length=3)),
                ('ngaysinh', models.DateField(blank=True, db_column='NGAYSINH', null=True)),
                ('sdt', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SDT', max_length=10)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EMAIL', max_length=50, null=True)),
            ],
            options={
                'db_table': 'NGUOIDUNG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phanquyen',
            fields=[
                ('maquyen', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MAQUYEN', max_length=5, primary_key=True, serialize=False)),
                ('tenquyen', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TENQUYEN', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'PHANQUYEN',
                'managed': False,
            },
        ),
    ]
