# Generated by Django 4.2.4 on 2023-09-26 18:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Baidang',
            fields=[
                ('id_baidang', models.BigIntegerField(db_column='ID_BAIDANG', primary_key=True, serialize=False)),
                ('tieude', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TIEUDE', max_length=100, null=True)),
                ('loai', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LOAI', max_length=7)),
                ('diachi', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DIACHI', max_length=30)),
                ('huyen', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='HUYEN', max_length=30)),
                ('quan', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='QUAN', max_length=20)),
                ('tinh', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TINH', max_length=30)),
                ('giayto', models.BooleanField(db_column='GIAYTO')),
                ('sopn', models.IntegerField(db_column='SOPN')),
                ('tinhtrang', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TINHTRANG', max_length=20, null=True)),
                ('dientich', models.FloatField(db_column='DIENTICH')),
                ('dai', models.FloatField(db_column='DAI')),
                ('rong', models.FloatField(db_column='RONG')),
                ('giaban', models.DecimalField(db_column='GIABAN', decimal_places=4, max_digits=19)),
                ('chitiet', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CHITIET', null=True)),
                ('trangthai', models.IntegerField(db_column='TRANGTHAI')),
                ('chudang', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CHUDANG', max_length=10)),
                ('ngaydang', models.DateField(db_column='NGAYDANG', default=datetime.datetime(2023, 9, 26, 18, 6, 53, 375402))),
                ('ngayban', models.DateField(blank=True, db_column='NGAYBAN', null=True)),
            ],
            options={
                'db_table': 'BAIDANG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hinhanh',
            fields=[
                ('id_hinhanh', models.BigIntegerField(db_column='ID_HINHANH', primary_key=True, serialize=False)),
                ('nguon', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NGUON', max_length=100)),
            ],
            options={
                'db_table': 'HINHANH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nguoidung',
            fields=[
                ('tendangnhap', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TENDANGNHAP', max_length=20, primary_key=True, serialize=False)),
                ('matkhau', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MATKHAU', max_length=20)),
                ('khoa', models.BooleanField(db_column='KHOA')),
                ('ho', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='HO', max_length=50)),
                ('ten', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TEN', max_length=20)),
                ('gioitinh', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='GIOITINH', max_length=3)),
                ('ngaysinh', models.DateField(blank=True, db_column='NGAYSINH', null=True)),
                ('sdt', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SDT', max_length=10)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EMAIL', max_length=50, null=True)),
            ],
            options={
                'db_table': 'NGUOIDUNG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phanquyen',
            fields=[
                ('maquyen', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MAQUYEN', max_length=5, primary_key=True, serialize=False)),
                ('tenquyen', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TENQUYEN', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'PHANQUYEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chungcu',
            fields=[
                ('machungcu', models.OneToOneField(db_column='MACHUNGCU', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.baidang')),
                ('lo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LO', max_length=10, null=True)),
                ('macan', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MACAN', max_length=10)),
                ('sotang', models.IntegerField(blank=True, db_column='SOTANG', null=True)),
                ('huong', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='HUONG', max_length=10, null=True)),
            ],
            options={
                'db_table': 'CHUNGCU',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DsYeuthich',
            fields=[
                ('tendangnhap', models.OneToOneField(db_column='TENDANGNHAP', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.nguoidung')),
            ],
            options={
                'db_table': 'DS_YEUTHICH',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nha',
            fields=[
                ('manha', models.OneToOneField(db_column='MANHA', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.baidang')),
                ('loaihinh', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LOAIHINH', max_length=20, null=True)),
                ('sotang', models.IntegerField(db_column='SOTANG')),
            ],
            options={
                'db_table': 'NHA',
                'managed': False,
            },
        ),
    ]
